### PR TITLE
Add .babelrc to .npmignore

### PR DESCRIPTION
**Pull request by alexicum**
Using removed Babel 5 option: base.stage: https://github.com/gaearon/disposables/issues/6

### CODE REVIEW

**Comment by dmarczydlo** [comment]
Could somebody can merge this?

**Comment by chrisprobably** [comment]
Please merge

**Comment by amccloud** [comment]
@gaearon It would really help solve an ongoing issue with react-dnd if you merge and release this https://github.com/react-dnd/react-dnd/issues?utf8=%E2%9C%93&q=disposables

**Comment by kuzzmi** [comment]
@gaearon Please, take a look at this. This is a big issue for using react-dnd, which is supposed to be better maintained than this package.

**Comment by youknowriad** [comment]
Just a note that this is making `react-dnd` unusable with the parcel bundler. Granted that it could be fixed in the parcel bundler by allowing some configuration. ( Discussion happening here https://github.com/parcel-bundler/parcel/issues/13 )

But this is an easy fix that doesn't seem to harm the "disposables" package as the code is already transpiled in npm.

**Comment by gaearon** [comment]
I understand your concerns and will try to merge when I get a chance.

But **this is not supposed to be an issue unless your build configuration is grossly wrong** or you’re using a tool that made a bad design choice (in this case, Parcel).

You should not try to run Babel over third party dependencies. This is fragile and in most cases unnecessary. If you determined this is necessary for some packages, please scope this behavior to those specific packages.

**Comment by gaearon** [comment]
>which is supposed to be better maintained than this package

Excuse me but how is it “supposed to be better maintained”? Did you buy a license to React DnD?

If you want to **help maintain** it please file an issue in the main project and reach out to the current maintainers. Being patronizing about maintenance quality on an open source project won’t get you anywhere.

Especially considering the issue is the problem with your build setup and not with the library.

**Comment by gaearon** [comment]
I changed my mind on merging this. Again, there is nothing this package is doing wrong. If you’re seeing this error you are mistakingly trying to compile packages in `node_modules` with Babel. You shouldn’t do this because it’s slow and because as a package author I have no idea if it will break my already compiled code. So instead you should change your build configuration to exclude either all packages from Babel compilation, or at least this one.

**Comment by gaearon** [comment]
OK, I published 1.0.2 that "fixes" this.

I still think that the real problem is in your build setup if you're affected by this, and you should fix it.

However, I presume most people in this thread have probably figured it out already (since the issue is pretty old). On the other hand, I don't want to be an obstacle to Parcel adoption.

Still, if you're affected by this, it will keep happening for you because other projects will include configs that become incompatible with time. So your setup is fragile and you should fix it.

**Comment by youknowriad** [comment]
Thank you 👍

**Pull request closed without merging**
